import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layouts/root/Navbar";
import Footer from "@/components/layouts/root/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-white dark:bg-black dark:text-white font-open-sans">
          <div className="lg:px-28 lg:pt-6 ">
            <Navbar></Navbar>
            {children}
          </div>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
